### ISSUE TITLE
option to make draft pages

### ISSUE THREAD

**Issue by sw-yx** [danielhusar/gatsby-theme-spring#1]
thanks for this project! its really high quality!

ok my user story: i like having my drafts out in the open.

https://github.com/danielhusar/gatsby-theme-spring/blob/master/theme/gatsby-node.js#L49

this line filters out all drafts, which makes it hard to do that. 

ideally what i'm thinking is that drafts would be generated, maybe have a prefix URL/maybe not, but just not displayed on the main page. get what i mean? so i can privately share by url. and i can control the display with the templates on my end.

it all starts with that one query tho. how about dropping it?

**Comment by danielhusar** [comment]
Sounds good :)
Maybe those generated draft should have also noindex for google?

**Comment by sw-yx** [comment]
ooh good idea

**Comment by sw-yx** [comment]
nice!
